### ISSUE TITLE
generisches maskulinum

### ISSUE THREAD

**Issue by Flixi1403** [simonneutert/rennrad-rheinhessen-event-formular#2]
Generisches Maskulinum (Mitfahrer) liest sich schlanker, aber weil sich ja gerade die Gruppenfahrten unbedingt auch an Frauen richten kann man vielleicht "Mitfahrerinnen und Mitfahrer" oder Mitfahrer*innen schreiben. Kann das auch gerne einpflegen, falls gewünscht...

**Comment by simonneutert** [comment]
absolut gewünscht, vielen Dank @Flixi1403 ❤️

**Comment by Flixi1403** [comment]
Erledigt mit #3
